### ISSUE TITLE
Диаграмма вариантов использования

### ISSUE THREAD

**Issue by artemkurylev** [IKaSeI/RPIS_PAGE#1]
Здесь обсуждаем диаграмму ВИ и все, что с ней связано

**Comment by IKaSeI** [comment]
Отношение включения указывает на то, что поведение одного прецедента включается в некоторой точке в другой прецедент в качестве составного компонента. Особенности включения заключаются в том, что включаемый прецедент должен быть обязательным для дополняемого (включение должно быть безусловным, а дополняемый вариант использования без включения не сможет выполняться), т.е. это это отношение задает очень сильную связь.

(С) Из сети.
-------------------------------------------------------------------------------------------------------
Отношение зависимости (dependency) определяется как форма взаимосвязи между двумя элементами модели, предназначенная для спецификации того обстоятельства, что изменение одного элемента модели приводит к изменению некоторого другого элемента
Отношение включения (include) специфицирует тот факт, что некоторый вариант использования содержит поведение, определенное в другом варианте использования 

(С) Из лекции Игнатьева.
-------------------------------------------------------------------------------------------------------

Вот ещё статья http://www.nnre.ru/kompyutery_i_internet/samouchitel_uml/p4.php
там в конце про включение.
--------------------------------------------------------------------------------------------------------

Итого мне не нравится и связь наследования в Анином варианте диаграммы и связь включения. Конечно же, обе диаграммы надо доработать.

На счет включения - его можно оставить, если поиск заявок будет происходить только при помощи поиска. А тут напрашивается ещё то, что я могу вне поиска листать заявки. Вероятно, лучше поменять на связь расширения.

Имеющаяся связь расширение на диаграмме - в каком случае мне придется прибегнуть к поиску, чтобы посмотреть информацию о чужой заявке, а в каком я обойдусь без помощи поиска? Мне кажется, что поиск используется всегда в том или ином виде. Здесь включение.
